### ISSUE TITLE
Switching to light mode should also switch pictures to light mode.

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/website#106]
I'm not a big fan of light mode but even so, here is how it looks like:
![image](https://user-images.githubusercontent.com/72760579/106333108-fe1d3000-6255-11eb-91f3-53226925278e.png)
As you can see, the theme is light mode, but the pictures are not. So it the user switches theme on the website, it should also switch the theme of the pictures...
![image](https://user-images.githubusercontent.com/72760579/106333186-20af4900-6256-11eb-8cd8-082b1afe9c68.png)
Speaking of pictures... when are we going to have new ones?

**Comment by Hans5958** [comment]
There will be more pictures, which means the size of the repo will be bigger, but I guess that is okay?

Also, it seems that I need to update it due to the fact that there is a new tab on the popup, which is "Addon". Will try to do it when I have time.

**Comment by TheColaber** [comment]
> the size of the repo will be bigger, but I guess that is okay
Yes? Not a big problem.

**Comment by Hans5958** [comment]
Resolved on 2b43579b59140bfdc02d807e52c30ecfc6938ec5
