### ISSUE TITLE
Tidy up (and changing) WorldLanguages changes

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website#12]
To whom it might concern, I wil review the changes that WL did on his descriptively-named `"Stuff" :P` commit. Will also answer future issues on here.

ETA this Saturday, or even as soon as Friday, after I done with manifest-schema.

**Comment by GrahamSH-LLK** [comment]
You should probably add my changes here too. I don't trust myself enough to think that there are _no_ bugs in my code.
