### ISSUE TITLE
Addons list on mobile

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/website#121]
On mobile, the list view of the addons list does not look good at all. It should be disabled on mobile.

**Comment by Hans5958** [comment]
Eh, that does not mean that it is not good at all. It's just because the width of the viewport that the view looks funny. I might can fix this by just hiding the image on phones. We'll see?

**Comment by RedGuy12** [comment]
But it looks good on grid view. I was thinking his the view toggle button.
________________________________
