### ISSUE TITLE
make footer stick to bottom of page

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/website#13]
looks funny when not enough content, i think you can just make the body display flex and it should:tm: work

**Comment by Hans5958** [comment]
Will be fixed as part on #12. Somehow WL broke the flex. Don't know what happened, but yeah.

**Comment by JeffaloBob** [comment]
ok wl weird flex but ok

**Comment by WorldLanguages** [comment]
Lol I broke it? interesting
