### ISSUE TITLE
I have only two commit on the SA repo but the website said I have 3 commit

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [ScratchAddons/website#133]
photo
<img width="1278" alt="ภาพถ่ายหน้าจอ 2564-03-19 เวลา 20 38 42" src="https://user-images.githubusercontent.com/66320961/111788898-31457c80-88f3-11eb-849a-ce0ae7f25357.png">
<img width="268" alt="ภาพถ่ายหน้าจอ 2564-03-19 เวลา 20 38 37" src="https://user-images.githubusercontent.com/66320961/111788910-34406d00-88f3-11eb-81a9-c5f29852f617.png">

**Comment by Hans5958** [comment]
There's one more. Keep in mind that this is aggregated from all repositories on the org.

https://github.com/ScratchAddons/contributors/commits?author=scratchusernamemrtbts&until=2021-03-19

**Comment by scratchusernamemrtbts** [comment]
Oh
