### ISSUE TITLE
Bug in the  2D Colorpicker

### ISSUE THREAD

**Issue by BarionLP** [ScratchAddons/website#139]
I don't know how to describe, just look in the Video

I'm using Firefox on Win 10

https://user-images.githubusercontent.com/76686287/113129717-83ec3600-921b-11eb-9805-c8b22f6bd386.mp4

**Comment by BarionLP** [comment]
Sorry, wrong repository

**Comment by RedGuy12** [comment]
I think this was fixed.
________________________________
