### ISSUE TITLE
Web Messaging

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/website#143]
A page that shows the Scratch Messaging page from SA, but on the website. Useful for mobile users

**Comment by RedGuy12** [comment]
just click the icon smh

**Comment by mxmou** [comment]
Probably impossible. There is no way for the Scratch Addons website to log into your Scratch account.

**Comment by RedGuy12** [comment]
Nah, it’s possible if you give your username and password.

Also, this would need a server because of CORS.

**Comment by TheColaber** [comment]
> give your username and password

and that's the red flag... i think we can just show a msg count, but this feels useless when the extension is a thing...

**Comment by WorldLanguages** [comment]
No
