### ISSUE TITLE
I kinda want credit

### ISSUE THREAD

**Issue by Ani-Xan** [ScratchAddons/website#19]
If you look at [https://explosion-scratch.github.io/scratchaddons.github.io/contributors.html](https://explosion-scratch.github.io/scratchaddons.github.io/contributors.html#readable_list:~:text=Ani%2DXan), I am credited. That kinda feels nice. Could I be credited on this website too? (for contributing many addon ideas and as @--Explosion-- states on the website, "Fixing bugs occasionally".)
Sorry if I'm being rude. 
◑﹏◐

**Comment by Hans5958** [comment]
The data based is the contributions on repositories across the organization. Doing this will require some changes on the website. I'll see what I can do in a later meantime.

**Comment by Ani-Xan** [comment]
Okay! 😊
