### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by BoomerScratch** [ScratchAddons/website#22]
**Is your feature request related to a problem? Please describe.**

Sometimes people don't know how to use the extension.

**Describe the solution you'd like**

A 'welcome screen' which appears at first run. It doesn't open in a new tab; it appears in the popup and some other pages. It shows the user a tutorial on how to use the extension. (for example, enable/disable an addon)

**Comment by WorldLanguages** [comment]
I transferred this issue because it's likely a good idea for new users. Old Scratch Messaging Extension users got directed to the settings page pretty heavily, we should likely do the same with new users.

**Comment by Hans5958** [comment]
I have made a welcome, farewell, and a FAQ page with it's initial contents. Everyone may collaborate with the contents.

**Comment by GrahamSH-LLK** [comment]
That sounds good. But seriously, **don't** even think about having it make a new tab. That's so annoying.

**Comment by WorldLanguages** [comment]
@GrahamSH-LLK Why tho? The user just installed the extension. They should be expecting a new tab. The main issue with stupid new tabs I see are update changelogs.

**Comment by GrahamSH-LLK** [comment]
Because chrome sync, and school Chromebooks. When the extension gets synced and installs, or every time you sign into school Chromebook (they don't save your data. see below for an interesting story) you get the screen. The first time, it's not annoying, but after you see it 100+ times, you uninstall the extension.

<details> <summary> story </summary> 
It turns out, the setting that makes it so that they don't save data beyond signout <I>allocates 1/2 the ram</i> to store the details. Instant slowdown, but, they're chromebooks.
</details>

**Comment by WorldLanguages** [comment]
> every time you sign into school Chromebook you get the screen

Really? Does Chrome fire the "install" event on every startup on some school Chromebooks?

**Comment by GrahamSH-LLK** [comment]
Yeah.

**Comment by WorldLanguages** [comment]
@GrahamSH-LLK does local storage / extension storage persist between "sessions"? Any workaround to know if it's actually an installation?

**Comment by GrahamSH-LLK** [comment]
It depends on the setup, but most Chromebooks that are setup to be on a "cart" allocate 1/2 the ram for that stuff, which gets cleared every session.

**Comment by WorldLanguages** [comment]
@GrahamSH-LLK Extension settings (which are stored in chrome.storage) are cleared every session??? If that's the case, Scratch Addons won't be very useful to them, since they'll have to set it up every time D:

**Comment by Hans5958** [comment]
Done as https://github.com/ScratchAddons/website/commit/b09ca3c19cf5b409d03ad74c04cec3c169bb0d1c. Now to implement it. @WorldLanguages

**Comment by Hans5958** [comment]
I still think that the mentioned oversight should have been mitigated by someone on Chrome. I still being optimistic that extension settings should still be synced by the browser to our Google accounts.

Also, I don't think a minority should stop a feature to be added. I still don't know about the OS majority of our users.

**Comment by GrahamSH-LLK** [comment]
This is done.
