### ISSUE TITLE
[Feature] 'Goodbye' page

### ISSUE THREAD

**Issue by BoomerScratch** [ScratchAddons/website#23]
[`chrome.runtime.setUninstallURL`](https://developer.chrome.com/extensions/runtime#method-setUninstallURL) will open an URL once the extension gets uninstalled. It can link to a 'goodbye' page which tells the user to give feedback if they have (using GitHub issues).

**Comment by Explosion-Scratch** [comment]
It seems this has been implemented, I'll close it for now!

**Comment by WorldLanguages** [comment]
It hasn't, what am I missing here? 🤔

**Comment by WorldLanguages** [comment]
Ohh, this has been moved from the extension repo to this one

**Comment by Explosion-Scratch** [comment]
XD

**Comment by Hans5958** [comment]
> 
> 
> It seems this has been implemented, I'll close it for now!

You sure? I only made the foundations. The page itself is still empty.

**Comment by WorldLanguages** [comment]
Tbh I'd redirect farewell to feedback for now

**Comment by BoomerScratch** [comment]
Closing because PR ScratchAddons/ScratchAddons#437 has been merged.

**Comment by Hans5958** [comment]
This issue shouldn't have closed because the farewell page is incomplete. I have opened #30 as the continuation of this issue, and also to avoid confusion.
