### ISSUE TITLE
Multiple languages support

### ISSUE THREAD

**Issue by jemunm378** [ScratchAddons/website#25]
I think there should be a dropdown menu to change the website languages.

**Comment by WorldLanguages** [comment]
Hmm, this would be nice but we're still far away from having the extension itself localized.

**Comment by Explosion-Scratch** [comment]
Also we'd need translators and people who speak multiple languages.

**Comment by jemunm378** [comment]
@WorldLanguages @Explosion-Scratch Alright!

**Comment by BoomerScratch** [comment]
Hmm... Translate the extension or scratchaddons.com?

**Comment by BoomerScratch** [comment]
Should we do this for the extension too?

**Comment by GrahamSH-LLK** [comment]
We probably _will_, but for now, it's not a huge priority afaik.

**Comment by WorldLanguages** [comment]
> Should we do this for the extension too?

It's planned, and there's already an issue for it.

**Comment by RedGuy12** [comment]
You could use the Google translate api...I know it's not the best but we dont have translators...I know there's a widget for wordpress so it should be kinda easy

**Comment by GrahamSH-LLK** [comment]
> You could use the Google translate api...I know it's not the best but we dont have translators...I know there's a widget for wordpress so it should be kinda easy

A. We actually do.
B. We don't use wordpress.....

**Comment by RedGuy12** [comment]
B. I know you dont, but i believe it's just an iframe from using inspect element on my WP site

Paul Reid

________________________________

**Comment by GrahamSH-LLK** [comment]
Still, we have a bunch of translators.

**Comment by RedGuy12** [comment]
Ok I didn't know

Paul Reid

________________________________

**Comment by TheColaber** [comment]
Last Convo was a month ago... any updates? I'm sure we would need a system like the one we currently use for our extension.
cc @Hans5958, @WorldLanguages, @apple502j

**Comment by scratchusernamemrtbts** [comment]
can we use transifex?

**Comment by Hans5958** [comment]
Eh, it's pretty slow, since I'm kinda focused on other aspects on SA and with my school. The system not going to be the same as the one's on the extension (look up hugo i18n). Of course TX is going to be used, but I'm still not sure whether it works on go-i18n. High hopes.

**Comment by cobaltt7** [comment]
Superseded by https://github.com/ScratchAddons/website-v2/issues/5
