### ISSUE TITLE
Logo cut off

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/website#29]
![image](https://user-images.githubusercontent.com/64214252/95205021-d2f86780-07b2-11eb-8089-81f2d26282d3.png)

**Comment by WorldLanguages** [comment]
Is that firefox? It looked ok on Chrome

**Comment by GrahamSH-LLK** [comment]
It's chrome, but I fixed it.

**Comment by WorldLanguages** [comment]
I guess it might depend in your font family and size settings, hmm
