### ISSUE TITLE
Complete farewell/uninstall page

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website#30]
This is a continuation of #23, to avoid confusion between the implementation on the extension and the page itself.

https://scratchaddons.com/farewell still looks empty, but the farewell page is already implemented in the extension. So, the page needs to get done for user experience.

**Comment by BoomerScratch** [comment]
Maybe add a reinstall button? And also a link to the Chrome Web Store support tab?

**Comment by BoomerScratch** [comment]
I think it is best to move the link to the Chrome Web Store support tab to the feedback page.

**Comment by Hans5958** [comment]
Done as https://github.com/ScratchAddons/website/commit/b09ca3c19cf5b409d03ad74c04cec3c169bb0d1c, sort of. It's still kind of empty, so if anyone wanted to add something on it then I would appreciate it.
