### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website#32]
Making the list of frequently asked questions right now. The file is on https://github.com/ScratchAddons/website/tree/faq/site/faq.md, if you wanted to know the current revision, and/or maybe wanted to help.

**Comment by GrahamSH-LLK** [comment]
@Hans5958 Is the FAQ ready to merge?

**Comment by Hans5958** [comment]
Not yet dude

**Comment by GrahamSH-LLK** [comment]
> Not yet dude

Why? What are we waiting for?

**Comment by Hans5958** [comment]
I'm actually still adding stuff on there. I just added some stuff there and I think it's closer to complete than ever. The only thing that holds me on right now is the link to a page that explains how to translate it, which still doesn't exist.

**Comment by WorldLanguages** [comment]
@Hans5958 Weird to see you think non-100%-complete-faq > no faq :P

**Comment by Hans5958** [comment]
You mean you prefer none at all? Also, it is like 99% because that single link.
