### ISSUE TITLE
Sorry!

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/website#33]
I meant to create a PR with my changes to the FAQ but I accidentally just committed to the main branch!

**Comment by Hans5958** [comment]
You mean you pushed it into the faq branch? I didn't see any builds regarding your commit.

It's okay anyways. The faq branch is not the production branch anyway.

**Comment by Explosion-Scratch** [comment]
Yeah, I must've done that to the FAQ branch. W_L said not to directly commit, but instead to make and merge PR's.

**Comment by Hans5958** [comment]
I guess he thinks that the current revision is in the `master` branch. This is still in the `faq` branch, so it won't appear on the website until it is merged.

**Comment by Explosion-Scratch** [comment]
I see.
