### ISSUE TITLE
Remove Discord Link

### ISSUE THREAD

**Issue by jemunm378** [ScratchAddons/website#5]
If your planning on sharing the website on the scratch website, you may have to remove the discord link. The ST doesn't allow any discord links.

**Comment by WorldLanguages** [comment]
For obvious reasons we don't plan to share the website on the Scratch website. Still, the Discord link should only be present in the repo's readme.

**Comment by jemunm378** [comment]
Okay 👍.

**Comment by Hans5958** [comment]
> If your planning on sharing the website on the scratch website, you may have to remove the discord link. The ST doesn't allow any discord links.

No, we don't. Sharing this addon is already a big no-no, let alone the Discord server. I am on the discussion with WL about it.
