### ISSUE TITLE
Help wanted: Complete images of each addon

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website#61]
I need your help with the addon screenshots. The addons page on https://scratchaddons.com/addons is quite boring, because there's only images for a select addon. I wanted to do it, but due to some circumstances, and the fact that it is quite tedious, I can't, so here's an issue for it.

The images for the addon are following these rules:
1. The file name is the addon ID, followed by the extension. The addon ID is the ones that colored gray and in the bottom of the addon name.
2. The file has an extension of `.png`
3. The image has a size of 400x300
3. The image contains a sample of what the addon can offer
4. If possible, the image is only cropped, without any resizing

Large images can also be added. Discuss it on ScratchAddons/ScratchAddons#364.

You can tell add these images by following either of these two options.

1. Create a fork, add your images on [/site/assets/images/addons](https://github.com/ScratchAddons/website/tree/master/site/assets/images/addons), and create a pull request.
2. Comment and attach the images on this issue.

**Comment by TheColaber** [comment]
I could help.

**Comment by TheColaber** [comment]
Some of these might need to be GIFs however because you can't really display 60fps in one photo.
Also, these images should show up all at once... maybe if we hover over an addon it shows up, or maybe there would be a button...

**Comment by Hans5958** [comment]
The images shows up at once. I have committed the changes, but I push the changes after I made this issue.

The images on that are mentioned here are simply for showcase, so it's either a simple `.png` picture, or none at all (as it is self-described on the description). I don't want to load `.gif` or video on the addons page because it will punish the load time and performance. However, images with other sizes and formats can be discussed on ScratchAddons/ScratchAddons#364.

**Comment by TheColaber** [comment]
Ok, so what tools do you use to crop? - Idk what to use...
![animated-thumbnail](https://user-images.githubusercontent.com/72760579/98470614-eaad7c00-21b4-11eb-8411-d17cd45e6e98.png)

**Comment by Hans5958** [comment]
> Ok, so what tools do you use to crop? - Idk what to use...
> ![animated-thumb](https://user-images.githubusercontent.com/72760579/98470614-eaad7c00-21b4-11eb-8411-d17cd45e6e98.png)
> 

I use paint.net and ShareX, but anything works as long as it is conforms with the requirements.

**Comment by mxmou** [comment]
I made a few.

Better emojis:
![Better emojis](https://user-images.githubusercontent.com/51849865/98851548-b3f69080-2456-11eb-9f45-69f2153d7c3e.png)

Clone counter:
![Clone counter](https://user-images.githubusercontent.com/51849865/98852103-75ada100-2457-11eb-96d7-578662a5c117.png)

Cloud games:
![Cloud games](https://user-images.githubusercontent.com/51849865/98852265-b7d6e280-2457-11eb-9b13-dd61e066d803.png)
*(Is this one okay? Some of the people whose usernames are in it might not like it.)*

Discuss button:
![Discuss button](https://user-images.githubusercontent.com/51849865/98852494-08e6d680-2458-11eb-84f9-603a3644365c.png)
*(Same concern as above)*

Colored context menus:
![Colored context menus](https://user-images.githubusercontent.com/51849865/98852745-6b3fd700-2458-11eb-81f4-904ae2c2b10d.png)

**Comment by mxmou** [comment]
Editor dark mode:
![Editor dark mode](https://user-images.githubusercontent.com/51849865/98853007-cc67aa80-2458-11eb-9a74-aa9889d04024.png)

Searchable dropdowns:
![Searchable dropdowns](https://user-images.githubusercontent.com/51849865/98853424-6c253880-2459-11eb-8a4b-ae2975e8ff6a.png)

Display stage on left side:
![Stage on left](https://user-images.githubusercontent.com/51849865/98853669-c6be9480-2459-11eb-9e6b-831ebfc11d90.png)

Customizable block colors:
![Customizable block colors](https://user-images.githubusercontent.com/51849865/98854059-5bc18d80-245a-11eb-8343-12eb6cf46661.png)

Show exact count:
![Exact count](https://user-images.githubusercontent.com/51849865/98854472-e2766a80-245a-11eb-9e14-26292e908158.png)

Forums search:
![Forums search](https://user-images.githubusercontent.com/51849865/98854669-22d5e880-245b-11eb-93b4-2fe16d012b58.png)

**Comment by mxmou** [comment]
Forums image uploader:
![Image uploader](https://user-images.githubusercontent.com/51849865/98855117-c9ba8480-245b-11eb-9c26-93b2e872927f.png)
*(I'm not sure if there's a good way to somehow emphasize the button in this one.)*

Live featured project:
![Live featured project](https://user-images.githubusercontent.com/51849865/98855396-35045680-245c-11eb-98c6-014eb94e4060.png)

Mouse position:
![Mouse position](https://user-images.githubusercontent.com/51849865/98855718-bd82f700-245c-11eb-9884-75dc5e4c69cd.png)

Pause button:
![Pause](https://user-images.githubusercontent.com/51849865/98855979-2d917d00-245d-11eb-87f2-5b6a07113363.png)

Remix tree button:
![Remix tree](https://user-images.githubusercontent.com/51849865/98856103-5dd91b80-245d-11eb-8007-8ecfb19818a5.png)

Confirm sprite deletion:
![Sprite deletion](https://user-images.githubusercontent.com/51849865/98856308-a5f83e00-245d-11eb-93e0-865d4afb3372.png)

**Comment by mxmou** [comment]
Resizable comment input:
![Resizable input](https://user-images.githubusercontent.com/51849865/98862643-8a923080-2467-11eb-8004-0ad6e366739d.png)

Scratch 2.0 → 3.0:
![Scratch 2.0 → 3.0](https://user-images.githubusercontent.com/51849865/98862823-ccbb7200-2467-11eb-904d-8a73ed6482dc.png)
*(Is there be a better way to show what this addon does?)*

Search profile:
![Search profile](https://user-images.githubusercontent.com/51849865/98863122-320f6300-2468-11eb-8766-320da9adbbd1.png)

Studio manager tools:
![Studio manager tools](https://user-images.githubusercontent.com/51849865/98863331-7e5aa300-2468-11eb-8adb-15b00d6b894a.png)

**Comment by Hans5958** [comment]
Okay, I have added it on my env a while ago. About the names, I think we can get away with that, possibly?

**Comment by mxmou** [comment]
> Okay, I have added it on my env a while ago. About the names, I think we can get away with that, possibly?

Probably.

**Comment by apple502j** [comment]
I'm not sure what picture we can use for some addons, though. For example, "fix SVG upload" and "bitmap copying" do not have any visible user interface.

**Comment by Hans5958** [comment]
@apple502j - I have addressed the issue when answering TheColaber's comment. It is a `.png` file, or not at all, so it is okay if there is no picture for some addons.

**Comment by mxmou** [comment]
**More images:**

Profile page banner:
![image](https://user-images.githubusercontent.com/51849865/103406795-3b5da780-4b5c-11eb-9744-8b53a6066178.png)

Block switching:
![image](https://user-images.githubusercontent.com/51849865/103406856-7b248f00-4b5c-11eb-92ea-28937257105f.png)

Confirm actions:
![image](https://user-images.githubusercontent.com/51849865/103406991-0f8ef180-4b5d-11eb-8f4d-cf6492204ae5.png)

Curator link:
![image](https://user-images.githubusercontent.com/51849865/103407070-6d233e00-4b5d-11eb-91fd-c66924ebc796.png)

Website dark mode:
![image](https://user-images.githubusercontent.com/51849865/103407110-98a62880-4b5d-11eb-8f68-4b34691ddf26.png)

Messages in editor:
![image](https://user-images.githubusercontent.com/51849865/103407158-c9865d80-4b5d-11eb-94cc-a5410d26c41c.png)

Customized quote & code blocks:
![image](https://user-images.githubusercontent.com/51849865/103407264-5af5cf80-4b5e-11eb-9483-d5cf6eea7130.png)

Show my-ocular status:
![image](https://user-images.githubusercontent.com/51849865/103407354-b0ca7780-4b5e-11eb-8d1b-8a22e5b7264b.png)

Onion skinnning:
![onionskin](https://user-images.githubusercontent.com/51849865/103407485-25051b00-4b5f-11eb-8f84-38b316dd7060.png)

Project progress bar:
![progress](https://user-images.githubusercontent.com/51849865/103407683-d1df9800-4b5f-11eb-8b1f-dedd282ce72b.png)

Sprite and script count:
![image](https://user-images.githubusercontent.com/51849865/103407783-2e42b780-4b60-11eb-8175-7ab59d9e94ab.png)

Project notes tabs:
![image](https://user-images.githubusercontent.com/51849865/103407872-706bf900-4b60-11eb-8372-eaf8b08f5d17.png)

YouTube full screen:
![image](https://user-images.githubusercontent.com/51849865/103407921-a6a97880-4b60-11eb-876d-f19cfc837e2f.png)

**Comment by thecoder876** [comment]
Umm, can I help @Hans5958?

**Comment by Hans5958** [comment]
> Umm, can I help @Hans5958?

Go ahead. I need some help in the first place. Just follow the guidelines and take a look at maximouse's.

**Comment by thecoder876** [comment]
I have a better screenshot for the image uploader:
![Image Uploader Screenshot](https://user-images.githubusercontent.com/76265544/104732123-a8646600-5734-11eb-8e2b-25c02705a86d.png)

**Comment by thecoder876** [comment]
I have a better screenshot for the image uploader:
![Image Uploader Screenshot](https://user-images.githubusercontent.com/76265544/104732276-e2ce0300-5734-11eb-9dee-eb4c36e0f2e0.png)

**Comment by Hans5958** [comment]
@thecoder876 Could you do with the 400x300 dimension? Also, I think it is better if you remove the red box.

**Comment by thecoder876** [comment]
> @thecoder876 Could you do with the 400x300 dimension? Also, I think it is better if you remove the red box.
Ok, but I added the red box so that you can see the button.

**Comment by Hans5958** [comment]
If you put the window, so it close the bottom half of the right icons, you can remove it.

**Comment by thecoder876** [comment]
> If you put the window, so it close the bottom half of the right icons, you can remove it.
> 
> Also, no resizing possible?

I'm doing it, but also busy with other stuff. I'll send when I can.

**Comment by Hans5958** [comment]
If you are quite busy, then go ahead. On second thought I think the current one is already adequate.

**Comment by iqnite** [comment]
![image](https://user-images.githubusercontent.com/50552317/106507834-e18a2d80-64cb-11eb-9689-f0fb1aa317a1.png)

ID: cat-blocks

**Comment by RedGuy12** [comment]
We don't need catblocks because they are secret
________________________________

**Comment by mxmou** [comment]
> We don't need catblocks because they are secret

There is a checkbox to show the secret ones too.

**Comment by Hans5958** [comment]
> ![image](https://user-images.githubusercontent.com/50552317/106507834-e18a2d80-64cb-11eb-9689-f0fb1aa317a1.png)
> 
> ID: cat-blocks

Please follow the format that I've set.

**Comment by z123w** [comment]
More links :
![More-links](https://user-images.githubusercontent.com/72137378/107000085-47bfca80-67c2-11eb-8274-d66b4a1f0bd0.png)

**Comment by TheColaber** [comment]
msg-count-badge:
![image](https://user-images.githubusercontent.com/72760579/109836652-5effa580-7c12-11eb-8396-6ac5cd9a5766.png)
60FPS:
![image](https://user-images.githubusercontent.com/72760579/109836925-a7b75e80-7c12-11eb-9415-c6607289d63f.png)
editor-stepping:
![image](https://user-images.githubusercontent.com/72760579/109837256-fd8c0680-7c12-11eb-98c9-75a0c453c0e6.png)
color-picker:
![image](https://user-images.githubusercontent.com/72760579/109837708-73906d80-7c13-11eb-9228-70a7bb7c387e.png)
comment-linebreaks:
![image](https://user-images.githubusercontent.com/72760579/109838574-498b7b00-7c14-11eb-904d-8041504eb58e.png)

**Comment by thecoder876** [comment]
gh is saying i was mentioned here, who pinged?

**Comment by mxmou** [comment]
> gh is saying i was mentioned here, who pinged?

https://github.com/ScratchAddons/website/issues/61#issuecomment-760944111
Once you're mentioned you will receive all notifications from that issue until you unsubscribe.

**Comment by iqnite** [comment]
copy-message-link
![image](https://user-images.githubusercontent.com/50552317/109993160-48d61000-7d0c-11eb-8dc3-74e3bef287f2.png)

**Comment by iqnite** [comment]
data-category-tweaks-v2
![image](https://user-images.githubusercontent.com/50552317/109993481-a23e3f00-7d0c-11eb-8900-b0ed8e173551.png)

**Comment by iqnite** [comment]
full-signature
![image](https://user-images.githubusercontent.com/50552317/109993799-f2b59c80-7d0c-11eb-9808-495af2210183.png)

**Comment by mxmou** [comment]
@iqnite Please crop screenshots to 400x300 pixels.

**Comment by iqnite** [comment]
hide-flyout
![image](https://user-images.githubusercontent.com/50552317/109994014-2ee8fd00-7d0d-11eb-9603-e889ca2b670b.png)

**Comment by iqnite** [comment]
mediarecorder 
![image](https://user-images.githubusercontent.com/50552317/109994311-7d969700-7d0d-11eb-8d37-e2c4e1958459.png)

**Comment by iqnite** [comment]
mute-project
![image](https://user-images.githubusercontent.com/50552317/109994480-a585fa80-7d0d-11eb-8dfd-acb8a22e9b14.png)

**Comment by Hans5958** [comment]
@TheColaber Will add later or some time!

@iqnite Could you please follow the format? Look at the examples on the website, or TheCollaber's, or mxmou's.

**Comment by RedGuy12** [comment]
block pallate icons
![image](https://user-images.githubusercontent.com/61329810/110971514-97913480-8320-11eb-92af-e5c8640db950.png)

copy link
![image](https://user-images.githubusercontent.com/61329810/110973252-9e20ab80-8322-11eb-9c8d-ce1fefa33446.png)

**Comment by TheColaber** [comment]
Addons Left (as of now):
- [ ] a11y
- [ ] Bitmap images copying
- [ ] Disable auto-save
- [ ] Feature unshared projects
- [ ] Fix broken SVG uploads
- [ ] Forums time zone
- [x] Show full areas
- [x] Auto-hide block palette
- [ ] Infinite scrolling
- [x] Last edit tooltip
- [ ] Auto-show editor extensions
- [x] Record project video
- [x] More links
- [ ] True forums YouTube links.

![image](https://user-images.githubusercontent.com/72760579/114559688-fefd1580-9c39-11eb-8d14-5c40ae90a481.png)
![image](https://user-images.githubusercontent.com/72760579/114560188-716df580-9c3a-11eb-9c01-d461bf868ae7.png)
![image](https://user-images.githubusercontent.com/72760579/114561056-3c15d780-9c3b-11eb-853b-82016385fe5d.png)
![image](https://user-images.githubusercontent.com/72760579/114561470-9747ca00-9c3b-11eb-93e4-225e0581488b.png)
![image](https://user-images.githubusercontent.com/72760579/114562060-25bc4b80-9c3c-11eb-9f4c-8f2033d089bf.png)

**Comment by Hans5958** [comment]
For the record, before I archive this repo, I wanted to tell that this issue is now moved to ScratchAddons/website-v2#4. So, for outsiders who wanted to contribute, please go to that issue instead.
