### ISSUE TITLE
Website and Extension Policy Notice

### ISSUE THREAD

**Issue by Ani-Xan** [ScratchAddons/website#64]
Hello, @ScratchAddons team! I want people to know about [**THIS**](https://scratch.mit.edu/discuss/topic/284272/) policy mentioned in the scratch forum so that they don't get themselves in trouble. (https://scratch.mit.edu/discuss/topic/284272/) 
There should be a notice on the ScratchAddons options page, the [website](https://scratchaddons.com/), and the extension download page telling users about the Extension/userscript policy mentioned above/in the forums. 

This has also been posted on the other repository for @ScratchAddons, linked **[here](https://github.com/ScratchAddons/ScratchAddons/issues/714)**.

**Comment by Hans5958** [comment]
I have made a mention about that a while ago in the FAQ page that is not released yet. The question is something along the lines of "Can I tell Scratch Addons on Scratch?" What do you think?

https://www.github.com/ScratchAddons/website/tree/faq/site%2Ffaq.md

**Comment by Ani-Xan** [comment]
@Hans5958 This is awesome. 🎉 Check out this post, mentioned you as well: https://github.com/ScratchAddons/ScratchAddons/issues/714#issuecomment-725048342
