### ISSUE TITLE
You made a typo

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/website#9]
![image](https://user-images.githubusercontent.com/61319150/93907117-91e85980-fcc2-11ea-84e9-ade9a50f131c.png)
lol

**Comment by WorldLanguages** [comment]
lol I don't see the typo

**Comment by WorldLanguages** [comment]
"some few" sounded weird but good enough :P

**Comment by GrahamSH-LLK** [comment]
It should be "a few".

**Comment by WorldLanguages** [comment]
Doesn't appear to be that incorrect? https://www.linguee.com/english-spanish/translation/some+few.html

**Comment by GrahamSH-LLK** [comment]
As far as I know, "a few" is at least more correct, and makes more sense than "some few".

**Comment by WorldLanguages** [comment]
For some reason my brain thought "some few seconds" meant more seconds than "a few seconds", and Glitch usually takes about 10 seconds to "warm up" so :P

**Comment by Explosion-Scratch** [comment]
Yeah. "Some few" is gramatically incorrect. It should be 'approximately 10 seconds' or 'a few seconds'

**Comment by WorldLanguages** [comment]
I see. @GrahamSH-LLK made a nice suggestion to "warm up" the Glitch server before the user types, so we could remove that all together; cases where it would take more than 2 seconds would be very rare.

**Comment by GrahamSH-LLK** [comment]
Still, if it does show, proper grammar is still important. I'm going to fix this.

**Comment by GrahamSH-LLK** [comment]
Fixed in latest commit.
